### ISSUE TITLE
How to downlaod nuScenes pkl_files and inst_database_train 

### ISSUE THREAD

**Issue by rayarit** [zhangzw12319/lcps#6]
nuScenes pkl_files and inst_database_train both download links are available but those are in baidu , not able to download those . Is there any other way to download those files ??
Or is there any way to train on nuScences dataset without pkl_files and inst_database_train ( inst_database_train_info.pkl) or any way to create those pkl files .
Thank you .

**Comment by zhangzw12319** [comment]
Sure, you can generate by "https://github.com/zhangzw12319/lcps/main/utils/prepare_nusc_inst_database.py" for NuScenes. As for SemanticKITTI you can refer to Panoptic-Polarnet `Instance preprocessing:` part.
