### ISSUE TITLE
Visualization for panoptic segmentation

### ISSUE THREAD

**Issue by rayari-1729** [zhangzw12319/lcps#7]
I used viz_projection.py . It gives semantic segmentation output , I want panoptic segmentation need to add instance segmentation. 
<img width="396" alt="Capture" src="https://github.com/zhangzw12319/lcps/assets/109236841/f23bf8e5-77aa-4ba5-9c18-2fc631a0c790">

**Comment by zhangzw12319** [comment]
You can find the visualization script for panoptic segmentation in the following GitHub repository: https://github.com/zhangzw12319/NuScenes-vis-api. The script allows you to load the panoptic prediction outputs in npz files and provides visualization tools to obtain panoptic segmentation results. Although the documentation in this repository is not fully completed, the project itself is functional and can be used. I hope this resolves your issue. If you find the project helpful, please feel free to give it a star. Thank you!

**Comment by rayari-1729** [comment]
Thank you :)
