### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by aselimc** [zhangzw12319/lcps#8]
Hello,

Is it possible to share approximately how long does it take to train the network in hours/days? 

Best

**Comment by zhangzw12319** [comment]
The training cost for nuScenes is high, usually requiring 8x GPUs to train for 120 epochs for final results. On 8x V100 32G, the training time is approximately 7-10 days (2h/epoch, 8 GPUs), but training for 60-70 epochs (3-4 days) can yield PQ results of around 76-78%, providing an approximation of the overall trend.

The training cost for SemanticKITTI is small, requiring only 1 GPU to train for 7 days (1.5h/epoch, 1 GPU).

**Comment by aselimc** [comment]
Thanks for the response.
