### ISSUE TITLE
Not able to download the pkl files - used in nuscenes dataloader 

### ISSUE THREAD

**Issue by charvi-077** [zhangzw12319/lcps#9]
As mentioned in the repo documentation regarding pkl file download, but I am unable to download pkl files for nuscenes dataloader from the given link, could you please provide the respective google drive or dropbox link ?

**Comment by zhangzw12319** [comment]
Hi, the google drive share link is also updated here `https://github.com/zhangzw12319/lcps/blob/main/docs/prepare_nusc.md`. Thanks for your information.

**Comment by charvi-077** [comment]
Thanks @zhangzw12319
